export {default as Intro} from './Intro'
export {default as Home} from './Home'
export {default as AboutHome} from './About/AboutHome'
export {default as AboutPage} from './About/AboutPage'
export {default as PortfolioSection} from './Portfolio/PortfolioSection'
export {default as Portfolio} from './Portfolio/Portfolio'
export {default as Footer} from './Footer/Footer'